AllCops:
  Include:
    - 'app/**/*'
    - 'spec/**/*'

  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Rails:
  Enabled: true
